name: .NET build, test, publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RELEASE: 1.8

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    needs: validate
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Publish
      run: dotnet publish /p:DebugType=None /p:DebugSymbols=false /p:PublishSingleFile=true --self-contained --output ./release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}-${{ env.RELEASE }}
        path: ./release/dotnet-publish-test${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: release-windows-latest-${{ env.RELEASE }}
        path: ./artifacts
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: release-ubuntu-latest-${{ env.RELEASE }}
        path: ./artifacts
    - name: Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE }}
        release_name: Release ${{ env.RELEASE }}
        body: |
          This is release ${{ env.RELEASE }}
        prerelease: false
    - name: Upload Windows artifacts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifacts/release-windows-latest-${{ env.RELEASE }}
    - name: Upload Linux artifacts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./artifacts/release-ubuntu-latest-${{ env.RELEASE }}
